name = "eeML"
uuid = "2681d317-7d5d-4753-b1ae-0ce8b1b15e9f"
authors = ["Eric Ekholm <eric.ekholm@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3.8.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
